#!/usr/bin/env bash
# This script reads /etc/passwd and displays the username, user ID, and home directory.

while IFS=":" read -r username _ uid _ _ _ home _; do
    echo "$username:$uid:$home"
done < /etc/passwd
