#!/usr/bin/env bash
# Trap SIGTERM and print "I am invincible!!!" instead of terminating
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop to print message
while true; do
    echo "To infinity and beyond"
    sleep 2
done
